/*
 * ESPRSSIF MIT License
 *
 * Copyright (c) 2015 <ESPRESSIF SYSTEMS (SHANGHAI) PTE LTD>
 *
 * Permission is hereby granted for use on ESPRESSIF SYSTEMS ESP32 only, in which case,
 * it is free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef _GPIO_SIG_REG_H
#define _GPIO_SIG_REG_H

#define SPICLK_IN_SEL_ADDR			GPIO_FUNC_IN_SEL0

#define SPICLK_IN_SEL				GPIO_GPIO_FUNC0_IN_SEL

#define SPICLK_IN_SEL_S				GPIO_GPIO_FUNC0_IN_SEL_S

#define SPICLK_IN_IDX				0

#define SPICLK_OUT_MUX_IDX			         0

#define SPIQ_IN_SEL_ADDR			GPIO_FUNC_IN_SEL0

#define SPIQ_IN_SEL				GPIO_GPIO_FUNC1_IN_SEL

#define SPIQ_IN_SEL_S				GPIO_GPIO_FUNC1_IN_SEL_S

#define SPIQ_IN_IDX				1

#define SPIQ_OUT_IDX			         1

#define SPID_IN_SEL_ADDR			GPIO_FUNC_IN_SEL0

#define SPID_IN_SEL				GPIO_GPIO_FUNC2_IN_SEL

#define SPID_IN_SEL_S				GPIO_GPIO_FUNC2_IN_SEL_S

#define SPID_IN_IDX				2

#define SPID_OUT_IDX			         2

#define SPIHD_IN_SEL_ADDR			GPIO_FUNC_IN_SEL0

#define SPIHD_IN_SEL				GPIO_GPIO_FUNC3_IN_SEL

#define SPIHD_IN_SEL_S				GPIO_GPIO_FUNC3_IN_SEL_S

#define SPIHD_IN_IDX				3

#define SPIHD_OUT_IDX			         3

#define SPIWP_IN_SEL_ADDR			GPIO_FUNC_IN_SEL0

#define SPIWP_IN_SEL				GPIO_GPIO_FUNC4_IN_SEL

#define SPIWP_IN_SEL_S				GPIO_GPIO_FUNC4_IN_SEL_S

#define SPIWP_IN_IDX				4

#define SPIWP_OUT_IDX			         4

#define SPICS0_IN_SEL_ADDR			GPIO_FUNC_IN_SEL1

#define SPICS0_IN_SEL				GPIO_GPIO_FUNC5_IN_SEL

#define SPICS0_IN_SEL_S				GPIO_GPIO_FUNC5_IN_SEL_S

#define SPICS0_IN_IDX				5

#define SPICS0_OUT_IDX			         5

#define SPICS1_IN_SEL_ADDR			GPIO_FUNC_IN_SEL1

#define SPICS1_IN_SEL				GPIO_GPIO_FUNC6_IN_SEL

#define SPICS1_IN_SEL_S				GPIO_GPIO_FUNC6_IN_SEL_S

#define SPICS1_IN_IDX				6

#define SPICS1_OUT_IDX			         6

#define SPICS2_IN_SEL_ADDR			GPIO_FUNC_IN_SEL1

#define SPICS2_IN_SEL				GPIO_GPIO_FUNC7_IN_SEL

#define SPICS2_IN_SEL_S				GPIO_GPIO_FUNC7_IN_SEL_S

#define SPICS2_IN_IDX				7

#define SPICS2_OUT_IDX			         7

#define HSPICLK_IN_SEL_ADDR			GPIO_FUNC_IN_SEL1

#define HSPICLK_IN_SEL				GPIO_GPIO_FUNC8_IN_SEL

#define HSPICLK_IN_SEL_S				GPIO_GPIO_FUNC8_IN_SEL_S

#define HSPICLK_IN_IDX				8

#define HSPICLK_OUT_MUX_IDX			         8

#define HSPIQ_IN_SEL_ADDR			GPIO_FUNC_IN_SEL1

#define HSPIQ_IN_SEL				GPIO_GPIO_FUNC9_IN_SEL

#define HSPIQ_IN_SEL_S				GPIO_GPIO_FUNC9_IN_SEL_S

#define HSPIQ_IN_IDX				9

#define HSPIQ_OUT_IDX			         9

#define HSPID_IN_SEL_ADDR			GPIO_FUNC_IN_SEL2

#define HSPID_IN_SEL				GPIO_GPIO_FUNC10_IN_SEL

#define HSPID_IN_SEL_S				GPIO_GPIO_FUNC10_IN_SEL_S

#define HSPID_IN_IDX				10

#define HSPID_OUT_IDX			         10

#define HSPICS0_IN_SEL_ADDR			GPIO_FUNC_IN_SEL2

#define HSPICS0_IN_SEL				GPIO_GPIO_FUNC11_IN_SEL

#define HSPICS0_IN_SEL_S				GPIO_GPIO_FUNC11_IN_SEL_S

#define HSPICS0_IN_IDX				11

#define HSPICS0_OUT_IDX			         11

#define HSPIHD_IN_SEL_ADDR			GPIO_FUNC_IN_SEL2

#define HSPIHD_IN_SEL				GPIO_GPIO_FUNC12_IN_SEL

#define HSPIHD_IN_SEL_S				GPIO_GPIO_FUNC12_IN_SEL_S

#define HSPIHD_IN_IDX				12

#define HSPIHD_OUT_IDX			         12

#define HSPIWP_IN_SEL_ADDR			GPIO_FUNC_IN_SEL2

#define HSPIWP_IN_SEL				GPIO_GPIO_FUNC13_IN_SEL

#define HSPIWP_IN_SEL_S				GPIO_GPIO_FUNC13_IN_SEL_S

#define HSPIWP_IN_IDX				13

#define HSPIWP_OUT_IDX			         13

#define U0RXD_IN_SEL_ADDR			GPIO_FUNC_IN_SEL2

#define U0RXD_IN_SEL				GPIO_GPIO_FUNC14_IN_SEL

#define U0RXD_IN_SEL_S				GPIO_GPIO_FUNC14_IN_SEL_S

#define U0RXD_IN_IDX				14

#define U0TXD_OUT_IDX			         14

#define U0CTS_IN_SEL_ADDR			GPIO_FUNC_IN_SEL3

#define U0CTS_IN_SEL				GPIO_GPIO_FUNC15_IN_SEL

#define U0CTS_IN_SEL_S				GPIO_GPIO_FUNC15_IN_SEL_S

#define U0CTS_IN_IDX				15

#define U0RTS_OUT_IDX			         15

#define U0DSR_IN_SEL_ADDR			GPIO_FUNC_IN_SEL3

#define U0DSR_IN_SEL				GPIO_GPIO_FUNC16_IN_SEL

#define U0DSR_IN_SEL_S				GPIO_GPIO_FUNC16_IN_SEL_S

#define U0DSR_IN_IDX				16

#define U0DTR_OUT_IDX			         16

#define U1RXD_IN_SEL_ADDR			GPIO_FUNC_IN_SEL3

#define U1RXD_IN_SEL				GPIO_GPIO_FUNC17_IN_SEL

#define U1RXD_IN_SEL_S				GPIO_GPIO_FUNC17_IN_SEL_S

#define U1RXD_IN_IDX				17

#define U1TXD_OUT_IDX			         17

#define U1CTS_IN_SEL_ADDR			GPIO_FUNC_IN_SEL3

#define U1CTS_IN_SEL				GPIO_GPIO_FUNC18_IN_SEL

#define U1CTS_IN_SEL_S				GPIO_GPIO_FUNC18_IN_SEL_S

#define U1CTS_IN_IDX				18

#define U1RTS_OUT_IDX			         18

#define I2CM_SCL_O_IDX			         19

#define I2CM_SDA_I_SEL_ADDR			GPIO_FUNC_IN_SEL4

#define I2CM_SDA_I_SEL				GPIO_GPIO_FUNC20_IN_SEL

#define I2CM_SDA_I_SEL_S				GPIO_GPIO_FUNC20_IN_SEL_S

#define I2CM_SDA_I_IDX				20

#define I2CM_SDA_O_IDX			         20

#define EXT_I2C_SCL_O_SEL_ADDR			GPIO_FUNC_IN_SEL4

#define EXT_I2C_SCL_O_SEL				GPIO_GPIO_FUNC21_IN_SEL

#define EXT_I2C_SCL_O_SEL_S				GPIO_GPIO_FUNC21_IN_SEL_S

#define EXT_I2C_SCL_O_IDX				21

#define EXT_I2C_SDA_O_SEL_ADDR			GPIO_FUNC_IN_SEL4

#define EXT_I2C_SDA_O_SEL				GPIO_GPIO_FUNC22_IN_SEL

#define EXT_I2C_SDA_O_SEL_S				GPIO_GPIO_FUNC22_IN_SEL_S

#define EXT_I2C_SDA_O_IDX				22

#define EXT_I2C_SDA_I_IDX			         22

#define I2SO_DATA_IN_SEL_ADDR			GPIO_FUNC_IN_SEL4

#define I2SO_DATA_IN_SEL				GPIO_GPIO_FUNC23_IN_SEL

#define I2SO_DATA_IN_SEL_S				GPIO_GPIO_FUNC23_IN_SEL_S

#define I2SO_DATA_IN_IDX				23

#define I2SO_DATA_OUT_IDX			         23

#define I2SO_BCK_IN_SEL_ADDR			GPIO_FUNC_IN_SEL4

#define I2SO_BCK_IN_SEL				GPIO_GPIO_FUNC24_IN_SEL

#define I2SO_BCK_IN_SEL_S				GPIO_GPIO_FUNC24_IN_SEL_S

#define I2SO_BCK_IN_IDX				24

#define I2SO_BCK_OUT_IDX			         24

#define I2SO_WS_IN_SEL_ADDR			GPIO_FUNC_IN_SEL5

#define I2SO_WS_IN_SEL				GPIO_GPIO_FUNC25_IN_SEL

#define I2SO_WS_IN_SEL_S				GPIO_GPIO_FUNC25_IN_SEL_S

#define I2SO_WS_IN_IDX				25

#define I2SO_WS_OUT_IDX			         25

#define I2SI_DATA_IN_SEL_ADDR			GPIO_FUNC_IN_SEL5

#define I2SI_DATA_IN_SEL				GPIO_GPIO_FUNC26_IN_SEL

#define I2SI_DATA_IN_SEL_S				GPIO_GPIO_FUNC26_IN_SEL_S

#define I2SI_DATA_IN_IDX				26

#define I2SI_DATA_OUT_IDX			         26

#define I2SI_BCK_IN_SEL_ADDR			GPIO_FUNC_IN_SEL5

#define I2SI_BCK_IN_SEL				GPIO_GPIO_FUNC27_IN_SEL

#define I2SI_BCK_IN_SEL_S				GPIO_GPIO_FUNC27_IN_SEL_S

#define I2SI_BCK_IN_IDX				27

#define I2SI_BCK_OUT_IDX			         27

#define I2SI_WS_IN_SEL_ADDR			GPIO_FUNC_IN_SEL5

#define I2SI_WS_IN_SEL				GPIO_GPIO_FUNC28_IN_SEL

#define I2SI_WS_IN_SEL_S				GPIO_GPIO_FUNC28_IN_SEL_S

#define I2SI_WS_IN_IDX				28

#define I2SI_WS_OUT_IDX			         28

#define I2CEXT0_SCL_IN_SEL_ADDR			GPIO_FUNC_IN_SEL5

#define I2CEXT0_SCL_IN_SEL				GPIO_GPIO_FUNC29_IN_SEL

#define I2CEXT0_SCL_IN_SEL_S				GPIO_GPIO_FUNC29_IN_SEL_S

#define I2CEXT0_SCL_IN_IDX				29

#define I2CEXT0_SCL_OUT_IDX			         29

#define I2CEXT0_SDA_IN_SEL_ADDR			GPIO_FUNC_IN_SEL6

#define I2CEXT0_SDA_IN_SEL				GPIO_GPIO_FUNC30_IN_SEL

#define I2CEXT0_SDA_IN_SEL_S				GPIO_GPIO_FUNC30_IN_SEL_S

#define I2CEXT0_SDA_IN_IDX				30

#define I2CEXT0_SDA_OUT_IDX			         30

#define SDIO_TOHOST_INT_OUT_IDX			         31

#define PWM_CAP_IN0_SEL_ADDR			GPIO_FUNC_IN_SEL6

#define PWM_CAP_IN0_SEL				GPIO_GPIO_FUNC32_IN_SEL

#define PWM_CAP_IN0_SEL_S				GPIO_GPIO_FUNC32_IN_SEL_S

#define PWM_CAP_IN0_IDX				32

#define PWM_OUT0_IDX			         32

#define PWM_CAP_IN1_SEL_ADDR			GPIO_FUNC_IN_SEL6

#define PWM_CAP_IN1_SEL				GPIO_GPIO_FUNC33_IN_SEL

#define PWM_CAP_IN1_SEL_S				GPIO_GPIO_FUNC33_IN_SEL_S

#define PWM_CAP_IN1_IDX				33

#define PWM_OUT1_IDX			         33

#define PWM_CAP_IN2_SEL_ADDR			GPIO_FUNC_IN_SEL6

#define PWM_CAP_IN2_SEL				GPIO_GPIO_FUNC34_IN_SEL

#define PWM_CAP_IN2_SEL_S				GPIO_GPIO_FUNC34_IN_SEL_S

#define PWM_CAP_IN2_IDX				34

#define PWM_OUT2_IDX			         34

#define PWM_FLT_IN0_SEL_ADDR			GPIO_FUNC_IN_SEL7

#define PWM_FLT_IN0_SEL				GPIO_GPIO_FUNC35_IN_SEL

#define PWM_FLT_IN0_SEL_S				GPIO_GPIO_FUNC35_IN_SEL_S

#define PWM_FLT_IN0_IDX				35

#define PWM_OUT3_IDX			         35

#define PWM_FLT_IN1_SEL_ADDR			GPIO_FUNC_IN_SEL7

#define PWM_FLT_IN1_SEL				GPIO_GPIO_FUNC36_IN_SEL

#define PWM_FLT_IN1_SEL_S				GPIO_GPIO_FUNC36_IN_SEL_S

#define PWM_FLT_IN1_IDX				36

#define PWM_OUT4_IDX			         36

#define GPIO_BT_ACTIVE_SEL_ADDR			GPIO_FUNC_IN_SEL7

#define GPIO_BT_ACTIVE_SEL				GPIO_GPIO_FUNC37_IN_SEL

#define GPIO_BT_ACTIVE_SEL_S				GPIO_GPIO_FUNC37_IN_SEL_S

#define GPIO_BT_ACTIVE_IDX				37

#define PWM_OUT5_IDX			         37

#define GPIO_BT_PRIORITY_SEL_ADDR			GPIO_FUNC_IN_SEL7

#define GPIO_BT_PRIORITY_SEL				GPIO_GPIO_FUNC38_IN_SEL

#define GPIO_BT_PRIORITY_SEL_S				GPIO_GPIO_FUNC38_IN_SEL_S

#define GPIO_BT_PRIORITY_IDX				38

#define PWM_OUT6_IDX			         38

#define PCNT_SIG_CH0_IN0_SEL_ADDR			GPIO_FUNC_IN_SEL7

#define PCNT_SIG_CH0_IN0_SEL				GPIO_GPIO_FUNC39_IN_SEL

#define PCNT_SIG_CH0_IN0_SEL_S				GPIO_GPIO_FUNC39_IN_SEL_S

#define PCNT_SIG_CH0_IN0_IDX				39

#define PWM_OUT7_IDX			         39

#define PCNT_SIG_CH1_IN0_SEL_ADDR			GPIO_FUNC_IN_SEL8

#define PCNT_SIG_CH1_IN0_SEL				GPIO_GPIO_FUNC40_IN_SEL

#define PCNT_SIG_CH1_IN0_SEL_S				GPIO_GPIO_FUNC40_IN_SEL_S

#define PCNT_SIG_CH1_IN0_IDX				40

#define GPIO_WLAN_ACTIVE_IDX			         40

#define PCNT_CTRL_CH0_IN0_SEL_ADDR			GPIO_FUNC_IN_SEL8

#define PCNT_CTRL_CH0_IN0_SEL				GPIO_GPIO_FUNC41_IN_SEL

#define PCNT_CTRL_CH0_IN0_SEL_S				GPIO_GPIO_FUNC41_IN_SEL_S

#define PCNT_CTRL_CH0_IN0_IDX				41

#define BB_DIAG0_IDX			         41

#define PCNT_CTRL_CH1_IN0_SEL_ADDR			GPIO_FUNC_IN_SEL8

#define PCNT_CTRL_CH1_IN0_SEL				GPIO_GPIO_FUNC42_IN_SEL

#define PCNT_CTRL_CH1_IN0_SEL_S				GPIO_GPIO_FUNC42_IN_SEL_S

#define PCNT_CTRL_CH1_IN0_IDX				42

#define BB_DIAG1_IDX			         42

#define PCNT_SIG_CH0_IN1_SEL_ADDR			GPIO_FUNC_IN_SEL8

#define PCNT_SIG_CH0_IN1_SEL				GPIO_GPIO_FUNC43_IN_SEL

#define PCNT_SIG_CH0_IN1_SEL_S				GPIO_GPIO_FUNC43_IN_SEL_S

#define PCNT_SIG_CH0_IN1_IDX				43

#define BB_DIAG2_IDX			         43

#define PCNT_SIG_CH1_IN1_SEL_ADDR			GPIO_FUNC_IN_SEL8

#define PCNT_SIG_CH1_IN1_SEL				GPIO_GPIO_FUNC44_IN_SEL

#define PCNT_SIG_CH1_IN1_SEL_S				GPIO_GPIO_FUNC44_IN_SEL_S

#define PCNT_SIG_CH1_IN1_IDX				44

#define BB_DIAG3_IDX			         44

#define PCNT_CTRL_CH0_IN1_SEL_ADDR			GPIO_FUNC_IN_SEL9

#define PCNT_CTRL_CH0_IN1_SEL				GPIO_GPIO_FUNC45_IN_SEL

#define PCNT_CTRL_CH0_IN1_SEL_S				GPIO_GPIO_FUNC45_IN_SEL_S

#define PCNT_CTRL_CH0_IN1_IDX				45

#define BB_DIAG4_IDX			         45

#define PCNT_CTRL_CH1_IN1_SEL_ADDR			GPIO_FUNC_IN_SEL9

#define PCNT_CTRL_CH1_IN1_SEL				GPIO_GPIO_FUNC46_IN_SEL

#define PCNT_CTRL_CH1_IN1_SEL_S				GPIO_GPIO_FUNC46_IN_SEL_S

#define PCNT_CTRL_CH1_IN1_IDX				46

#define BB_DIAG5_IDX			         46

#define PCNT_SIG_CH0_IN2_SEL_ADDR			GPIO_FUNC_IN_SEL9

#define PCNT_SIG_CH0_IN2_SEL				GPIO_GPIO_FUNC47_IN_SEL

#define PCNT_SIG_CH0_IN2_SEL_S				GPIO_GPIO_FUNC47_IN_SEL_S

#define PCNT_SIG_CH0_IN2_IDX				47

#define BB_DIAG6_IDX			         47

#define PCNT_SIG_CH1_IN2_SEL_ADDR			GPIO_FUNC_IN_SEL9

#define PCNT_SIG_CH1_IN2_SEL				GPIO_GPIO_FUNC48_IN_SEL

#define PCNT_SIG_CH1_IN2_SEL_S				GPIO_GPIO_FUNC48_IN_SEL_S

#define PCNT_SIG_CH1_IN2_IDX				48

#define BB_DIAG7_IDX			         48

#define PCNT_CTRL_CH0_IN2_SEL_ADDR			GPIO_FUNC_IN_SEL9

#define PCNT_CTRL_CH0_IN2_SEL				GPIO_GPIO_FUNC49_IN_SEL

#define PCNT_CTRL_CH0_IN2_SEL_S				GPIO_GPIO_FUNC49_IN_SEL_S

#define PCNT_CTRL_CH0_IN2_IDX				49

#define BB_DIAG8_IDX			         49

#define PCNT_CTRL_CH1_IN2_SEL_ADDR			GPIO_FUNC_IN_SEL10

#define PCNT_CTRL_CH1_IN2_SEL				GPIO_GPIO_FUNC50_IN_SEL

#define PCNT_CTRL_CH1_IN2_SEL_S				GPIO_GPIO_FUNC50_IN_SEL_S

#define PCNT_CTRL_CH1_IN2_IDX				50

#define BB_DIAG9_IDX			         50

#define PCNT_SIG_CH0_IN3_SEL_ADDR			GPIO_FUNC_IN_SEL10

#define PCNT_SIG_CH0_IN3_SEL				GPIO_GPIO_FUNC51_IN_SEL

#define PCNT_SIG_CH0_IN3_SEL_S				GPIO_GPIO_FUNC51_IN_SEL_S

#define PCNT_SIG_CH0_IN3_IDX				51

#define BB_DIAG10_IDX			         51

#define PCNT_SIG_CH1_IN3_SEL_ADDR			GPIO_FUNC_IN_SEL10

#define PCNT_SIG_CH1_IN3_SEL				GPIO_GPIO_FUNC52_IN_SEL

#define PCNT_SIG_CH1_IN3_SEL_S				GPIO_GPIO_FUNC52_IN_SEL_S

#define PCNT_SIG_CH1_IN3_IDX				52

#define BB_DIAG11_IDX			         52

#define PCNT_CTRL_CH0_IN3_SEL_ADDR			GPIO_FUNC_IN_SEL10

#define PCNT_CTRL_CH0_IN3_SEL				GPIO_GPIO_FUNC53_IN_SEL

#define PCNT_CTRL_CH0_IN3_SEL_S				GPIO_GPIO_FUNC53_IN_SEL_S

#define PCNT_CTRL_CH0_IN3_IDX				53

#define BB_DIAG12_IDX			         53

#define PCNT_CTRL_CH1_IN3_SEL_ADDR			GPIO_FUNC_IN_SEL10

#define PCNT_CTRL_CH1_IN3_SEL				GPIO_GPIO_FUNC54_IN_SEL

#define PCNT_CTRL_CH1_IN3_SEL_S				GPIO_GPIO_FUNC54_IN_SEL_S

#define PCNT_CTRL_CH1_IN3_IDX				54

#define BB_DIAG13_IDX			         54

#define PCNT_SIG_CH0_IN4_SEL_ADDR			GPIO_FUNC_IN_SEL11

#define PCNT_SIG_CH0_IN4_SEL				GPIO_GPIO_FUNC55_IN_SEL

#define PCNT_SIG_CH0_IN4_SEL_S				GPIO_GPIO_FUNC55_IN_SEL_S

#define PCNT_SIG_CH0_IN4_IDX				55

#define BB_DIAG14_IDX			         55

#define PCNT_SIG_CH1_IN4_SEL_ADDR			GPIO_FUNC_IN_SEL11

#define PCNT_SIG_CH1_IN4_SEL				GPIO_GPIO_FUNC56_IN_SEL

#define PCNT_SIG_CH1_IN4_SEL_S				GPIO_GPIO_FUNC56_IN_SEL_S

#define PCNT_SIG_CH1_IN4_IDX				56

#define BB_DIAG15_IDX			         56

#define PCNT_CTRL_CH0_IN4_SEL_ADDR			GPIO_FUNC_IN_SEL11

#define PCNT_CTRL_CH0_IN4_SEL				GPIO_GPIO_FUNC57_IN_SEL

#define PCNT_CTRL_CH0_IN4_SEL_S				GPIO_GPIO_FUNC57_IN_SEL_S

#define PCNT_CTRL_CH0_IN4_IDX				57

#define BB_DIAG16_IDX			         57

#define PCNT_CTRL_CH1_IN4_SEL_ADDR			GPIO_FUNC_IN_SEL11

#define PCNT_CTRL_CH1_IN4_SEL				GPIO_GPIO_FUNC58_IN_SEL

#define PCNT_CTRL_CH1_IN4_SEL_S				GPIO_GPIO_FUNC58_IN_SEL_S

#define PCNT_CTRL_CH1_IN4_IDX				58

#define BB_DIAG17_IDX			         58

#define BB_DIAG18_IDX			         59

#define BB_DIAG19_IDX			         60

#define HSPICS1_IN_SEL_ADDR			GPIO_FUNC_IN_SEL12

#define HSPICS1_IN_SEL				GPIO_GPIO_FUNC61_IN_SEL

#define HSPICS1_IN_SEL_S				GPIO_GPIO_FUNC61_IN_SEL_S

#define HSPICS1_IN_IDX				61

#define HSPICS1_OUT_IDX			         61

#define HSPICS2_IN_SEL_ADDR			GPIO_FUNC_IN_SEL12

#define HSPICS2_IN_SEL				GPIO_GPIO_FUNC62_IN_SEL

#define HSPICS2_IN_SEL_S				GPIO_GPIO_FUNC62_IN_SEL_S

#define HSPICS2_IN_IDX				62

#define HSPICS2_OUT_IDX			         62

#define VSPICLK_IN_SEL_ADDR			GPIO_FUNC_IN_SEL12

#define VSPICLK_IN_SEL				GPIO_GPIO_FUNC63_IN_SEL

#define VSPICLK_IN_SEL_S				GPIO_GPIO_FUNC63_IN_SEL_S

#define VSPICLK_IN_IDX				63

#define VSPICLK_OUT_MUX_IDX			         63

#define VSPIQ_IN_SEL_ADDR			GPIO_FUNC_IN_SEL12

#define VSPIQ_IN_SEL				GPIO_GPIO_FUNC64_IN_SEL

#define VSPIQ_IN_SEL_S				GPIO_GPIO_FUNC64_IN_SEL_S

#define VSPIQ_IN_IDX				64

#define VSPIQ_OUT_IDX			         64

#define VSPID_IN_SEL_ADDR			GPIO_FUNC_IN_SEL13

#define VSPID_IN_SEL				GPIO_GPIO_FUNC65_IN_SEL

#define VSPID_IN_SEL_S				GPIO_GPIO_FUNC65_IN_SEL_S

#define VSPID_IN_IDX				65

#define VSPID_OUT_IDX			         65

#define VSPIHD_IN_SEL_ADDR			GPIO_FUNC_IN_SEL13

#define VSPIHD_IN_SEL				GPIO_GPIO_FUNC66_IN_SEL

#define VSPIHD_IN_SEL_S				GPIO_GPIO_FUNC66_IN_SEL_S

#define VSPIHD_IN_IDX				66

#define VSPIHD_OUT_IDX			         66

#define VSPIWP_IN_SEL_ADDR			GPIO_FUNC_IN_SEL13

#define VSPIWP_IN_SEL				GPIO_GPIO_FUNC67_IN_SEL

#define VSPIWP_IN_SEL_S				GPIO_GPIO_FUNC67_IN_SEL_S

#define VSPIWP_IN_IDX				67

#define VSPIWP_OUT_IDX			         67

#define VSPICS0_IN_SEL_ADDR			GPIO_FUNC_IN_SEL13

#define VSPICS0_IN_SEL				GPIO_GPIO_FUNC68_IN_SEL

#define VSPICS0_IN_SEL_S				GPIO_GPIO_FUNC68_IN_SEL_S

#define VSPICS0_IN_IDX				68

#define VSPICS0_OUT_IDX			         68

#define VSPICS1_IN_SEL_ADDR			GPIO_FUNC_IN_SEL13

#define VSPICS1_IN_SEL				GPIO_GPIO_FUNC69_IN_SEL

#define VSPICS1_IN_SEL_S				GPIO_GPIO_FUNC69_IN_SEL_S

#define VSPICS1_IN_IDX				69

#define VSPICS1_OUT_IDX			         69

#define VSPICS2_IN_SEL_ADDR			GPIO_FUNC_IN_SEL14

#define VSPICS2_IN_SEL				GPIO_GPIO_FUNC70_IN_SEL

#define VSPICS2_IN_SEL_S				GPIO_GPIO_FUNC70_IN_SEL_S

#define VSPICS2_IN_IDX				70

#define VSPICS2_OUT_IDX			         70

#define PCNT_SIG_CH0_IN5_SEL_ADDR			GPIO_FUNC_IN_SEL14

#define PCNT_SIG_CH0_IN5_SEL				GPIO_GPIO_FUNC71_IN_SEL

#define PCNT_SIG_CH0_IN5_SEL_S				GPIO_GPIO_FUNC71_IN_SEL_S

#define PCNT_SIG_CH0_IN5_IDX				71

#define LEDC_HS_SIG_OUT0_IDX			         71

#define PCNT_SIG_CH1_IN5_SEL_ADDR			GPIO_FUNC_IN_SEL14

#define PCNT_SIG_CH1_IN5_SEL				GPIO_GPIO_FUNC72_IN_SEL

#define PCNT_SIG_CH1_IN5_SEL_S				GPIO_GPIO_FUNC72_IN_SEL_S

#define PCNT_SIG_CH1_IN5_IDX				72

#define LEDC_HS_SIG_OUT1_IDX			         72

#define PCNT_CTRL_CH0_IN5_SEL_ADDR			GPIO_FUNC_IN_SEL14

#define PCNT_CTRL_CH0_IN5_SEL				GPIO_GPIO_FUNC73_IN_SEL

#define PCNT_CTRL_CH0_IN5_SEL_S				GPIO_GPIO_FUNC73_IN_SEL_S

#define PCNT_CTRL_CH0_IN5_IDX				73

#define LEDC_HS_SIG_OUT2_IDX			         73

#define PCNT_CTRL_CH1_IN5_SEL_ADDR			GPIO_FUNC_IN_SEL14

#define PCNT_CTRL_CH1_IN5_SEL				GPIO_GPIO_FUNC74_IN_SEL

#define PCNT_CTRL_CH1_IN5_SEL_S				GPIO_GPIO_FUNC74_IN_SEL_S

#define PCNT_CTRL_CH1_IN5_IDX				74

#define LEDC_HS_SIG_OUT3_IDX			         74

#define PCNT_SIG_CH0_IN6_SEL_ADDR			GPIO_FUNC_IN_SEL15

#define PCNT_SIG_CH0_IN6_SEL				GPIO_GPIO_FUNC75_IN_SEL

#define PCNT_SIG_CH0_IN6_SEL_S				GPIO_GPIO_FUNC75_IN_SEL_S

#define PCNT_SIG_CH0_IN6_IDX				75

#define LEDC_HS_SIG_OUT4_IDX			         75

#define PCNT_SIG_CH1_IN6_SEL_ADDR			GPIO_FUNC_IN_SEL15

#define PCNT_SIG_CH1_IN6_SEL				GPIO_GPIO_FUNC76_IN_SEL

#define PCNT_SIG_CH1_IN6_SEL_S				GPIO_GPIO_FUNC76_IN_SEL_S

#define PCNT_SIG_CH1_IN6_IDX				76

#define LEDC_HS_SIG_OUT5_IDX			         76

#define PCNT_CTRL_CH0_IN6_SEL_ADDR			GPIO_FUNC_IN_SEL15

#define PCNT_CTRL_CH0_IN6_SEL				GPIO_GPIO_FUNC77_IN_SEL

#define PCNT_CTRL_CH0_IN6_SEL_S				GPIO_GPIO_FUNC77_IN_SEL_S

#define PCNT_CTRL_CH0_IN6_IDX				77

#define LEDC_HS_SIG_OUT6_IDX			         77

#define PCNT_CTRL_CH1_IN6_SEL_ADDR			GPIO_FUNC_IN_SEL15

#define PCNT_CTRL_CH1_IN6_SEL				GPIO_GPIO_FUNC78_IN_SEL

#define PCNT_CTRL_CH1_IN6_SEL_S				GPIO_GPIO_FUNC78_IN_SEL_S

#define PCNT_CTRL_CH1_IN6_IDX				78

#define LEDC_HS_SIG_OUT7_IDX			         78

#define PCNT_SIG_CH0_IN7_SEL_ADDR			GPIO_FUNC_IN_SEL15

#define PCNT_SIG_CH0_IN7_SEL				GPIO_GPIO_FUNC79_IN_SEL

#define PCNT_SIG_CH0_IN7_SEL_S				GPIO_GPIO_FUNC79_IN_SEL_S

#define PCNT_SIG_CH0_IN7_IDX				79

#define LEDC_LS_SIG_OUT0_IDX			         79

#define PCNT_SIG_CH1_IN7_SEL_ADDR			GPIO_FUNC_IN_SEL16

#define PCNT_SIG_CH1_IN7_SEL				GPIO_GPIO_FUNC80_IN_SEL

#define PCNT_SIG_CH1_IN7_SEL_S				GPIO_GPIO_FUNC80_IN_SEL_S

#define PCNT_SIG_CH1_IN7_IDX				80

#define LEDC_LS_SIG_OUT1_IDX			         80

#define PCNT_CTRL_CH0_IN7_SEL_ADDR			GPIO_FUNC_IN_SEL16

#define PCNT_CTRL_CH0_IN7_SEL				GPIO_GPIO_FUNC81_IN_SEL

#define PCNT_CTRL_CH0_IN7_SEL_S				GPIO_GPIO_FUNC81_IN_SEL_S

#define PCNT_CTRL_CH0_IN7_IDX				81

#define LEDC_LS_SIG_OUT2_IDX			         81

#define PCNT_CTRL_CH1_IN7_SEL_ADDR			GPIO_FUNC_IN_SEL16

#define PCNT_CTRL_CH1_IN7_SEL				GPIO_GPIO_FUNC82_IN_SEL

#define PCNT_CTRL_CH1_IN7_SEL_S				GPIO_GPIO_FUNC82_IN_SEL_S

#define PCNT_CTRL_CH1_IN7_IDX				82

#define LEDC_LS_SIG_OUT3_IDX			         82

#define RMT_SIG_IN0_SEL_ADDR			GPIO_FUNC_IN_SEL16

#define RMT_SIG_IN0_SEL				GPIO_GPIO_FUNC83_IN_SEL

#define RMT_SIG_IN0_SEL_S				GPIO_GPIO_FUNC83_IN_SEL_S

#define RMT_SIG_IN0_IDX				83

#define LEDC_LS_SIG_OUT4_IDX			         83

#define RMT_SIG_IN1_SEL_ADDR			GPIO_FUNC_IN_SEL16

#define RMT_SIG_IN1_SEL				GPIO_GPIO_FUNC84_IN_SEL

#define RMT_SIG_IN1_SEL_S				GPIO_GPIO_FUNC84_IN_SEL_S

#define RMT_SIG_IN1_IDX				84

#define LEDC_LS_SIG_OUT5_IDX			         84

#define RMT_SIG_IN2_SEL_ADDR			GPIO_FUNC_IN_SEL17

#define RMT_SIG_IN2_SEL				GPIO_GPIO_FUNC85_IN_SEL

#define RMT_SIG_IN2_SEL_S				GPIO_GPIO_FUNC85_IN_SEL_S

#define RMT_SIG_IN2_IDX				85

#define LEDC_LS_SIG_OUT6_IDX			         85

#define RMT_SIG_IN3_SEL_ADDR			GPIO_FUNC_IN_SEL17

#define RMT_SIG_IN3_SEL				GPIO_GPIO_FUNC86_IN_SEL

#define RMT_SIG_IN3_SEL_S				GPIO_GPIO_FUNC86_IN_SEL_S

#define RMT_SIG_IN3_IDX				86

#define LEDC_LS_SIG_OUT7_IDX			         86

#define RMT_SIG_IN4_SEL_ADDR			GPIO_FUNC_IN_SEL17

#define RMT_SIG_IN4_SEL				GPIO_GPIO_FUNC87_IN_SEL

#define RMT_SIG_IN4_SEL_S				GPIO_GPIO_FUNC87_IN_SEL_S

#define RMT_SIG_IN4_IDX				87

#define RMT_SIG_OUT0_IDX			         87

#define RMT_SIG_IN5_SEL_ADDR			GPIO_FUNC_IN_SEL17

#define RMT_SIG_IN5_SEL				GPIO_GPIO_FUNC88_IN_SEL

#define RMT_SIG_IN5_SEL_S				GPIO_GPIO_FUNC88_IN_SEL_S

#define RMT_SIG_IN5_IDX				88

#define RMT_SIG_OUT1_IDX			         88

#define RMT_SIG_IN6_SEL_ADDR			GPIO_FUNC_IN_SEL17

#define RMT_SIG_IN6_SEL				GPIO_GPIO_FUNC89_IN_SEL

#define RMT_SIG_IN6_SEL_S				GPIO_GPIO_FUNC89_IN_SEL_S

#define RMT_SIG_IN6_IDX				89

#define RMT_SIG_OUT2_IDX			         89

#define RMT_SIG_IN7_SEL_ADDR			GPIO_FUNC_IN_SEL18

#define RMT_SIG_IN7_SEL				GPIO_GPIO_FUNC90_IN_SEL

#define RMT_SIG_IN7_SEL_S				GPIO_GPIO_FUNC90_IN_SEL_S

#define RMT_SIG_IN7_IDX				90

#define RMT_SIG_OUT3_IDX			         90

#define RMT_SIG_OUT4_IDX			         91

#define RMT_SIG_OUT5_IDX			         92

#define RMT_SIG_OUT6_IDX			         93

#define RMT_SIG_OUT7_IDX			         94

#define I2CEXT1_SCL_IN_SEL_ADDR			GPIO_FUNC_IN_SEL19

#define I2CEXT1_SCL_IN_SEL				GPIO_GPIO_FUNC95_IN_SEL

#define I2CEXT1_SCL_IN_SEL_S				GPIO_GPIO_FUNC95_IN_SEL_S

#define I2CEXT1_SCL_IN_IDX				95

#define I2CEXT1_SCL_OUT_IDX			         95

#define I2CEXT1_SDA_IN_SEL_ADDR			GPIO_FUNC_IN_SEL19

#define I2CEXT1_SDA_IN_SEL				GPIO_GPIO_FUNC96_IN_SEL

#define I2CEXT1_SDA_IN_SEL_S				GPIO_GPIO_FUNC96_IN_SEL_S

#define I2CEXT1_SDA_IN_IDX				96

#define I2CEXT1_SDA_OUT_IDX			         96

#define HOST_CARD_DETECT_N_1_SEL_ADDR			GPIO_FUNC_IN_SEL19

#define HOST_CARD_DETECT_N_1_SEL				GPIO_GPIO_FUNC97_IN_SEL

#define HOST_CARD_DETECT_N_1_SEL_S				GPIO_GPIO_FUNC97_IN_SEL_S

#define HOST_CARD_DETECT_N_1_IDX				97

#define HOST_CCMD_OD_PULLUP_EN_N_IDX			         97

#define HOST_CARD_DETECT_N_2_SEL_ADDR			GPIO_FUNC_IN_SEL19

#define HOST_CARD_DETECT_N_2_SEL				GPIO_GPIO_FUNC98_IN_SEL

#define HOST_CARD_DETECT_N_2_SEL_S				GPIO_GPIO_FUNC98_IN_SEL_S

#define HOST_CARD_DETECT_N_2_IDX				98

#define HOST_RST_N_1_IDX			         98

#define HOST_CARD_WRITE_PRT_1_SEL_ADDR			GPIO_FUNC_IN_SEL19

#define HOST_CARD_WRITE_PRT_1_SEL				GPIO_GPIO_FUNC99_IN_SEL

#define HOST_CARD_WRITE_PRT_1_SEL_S				GPIO_GPIO_FUNC99_IN_SEL_S

#define HOST_CARD_WRITE_PRT_1_IDX				99

#define HOST_RST_N_2_IDX			         99

#define HOST_CARD_WRITE_PRT_2_SEL_ADDR			GPIO_FUNC_IN_SEL20

#define HOST_CARD_WRITE_PRT_2_SEL				GPIO_GPIO_FUNC100_IN_SEL

#define HOST_CARD_WRITE_PRT_2_SEL_S				GPIO_GPIO_FUNC100_IN_SEL_S

#define HOST_CARD_WRITE_PRT_2_IDX				100

#define GPIO_SD0_OUT_IDX			         100

#define HOST_CARD_INT_N_1_SEL_ADDR			GPIO_FUNC_IN_SEL20

#define HOST_CARD_INT_N_1_SEL				GPIO_GPIO_FUNC101_IN_SEL

#define HOST_CARD_INT_N_1_SEL_S				GPIO_GPIO_FUNC101_IN_SEL_S

#define HOST_CARD_INT_N_1_IDX				101

#define GPIO_SD1_OUT_IDX			         101

#define HOST_CARD_INT_N_2_SEL_ADDR			GPIO_FUNC_IN_SEL20

#define HOST_CARD_INT_N_2_SEL				GPIO_GPIO_FUNC102_IN_SEL

#define HOST_CARD_INT_N_2_SEL_S				GPIO_GPIO_FUNC102_IN_SEL_S

#define HOST_CARD_INT_N_2_IDX				102

#define GPIO_SD2_OUT_IDX			         102

#define GPIO_SD3_OUT_IDX			         103

#define GPIO_SD4_OUT_IDX			         104

#define GPIO_SD5_OUT_IDX			         105

#define GPIO_SD6_OUT_IDX			         106

#define GPIO_SD7_OUT_IDX			         107

#define GPIO_SD0_OUTB_IDX			         108

#define GPIO_SD1_OUTB_IDX			         109

#define GPIO_SD2_OUTB_IDX			         110

#define GPIO_SD3_OUTB_IDX			         111

#define LEDC_HS_SIG_OUTB0_IDX			         112

#define LEDC_HS_SIG_OUTB1_IDX			         113

#define LEDC_HS_SIG_OUTB2_IDX			         114

#define LEDC_LS_SIG_OUTB0_IDX			         115

#define LEDC_LS_SIG_OUTB1_IDX			         116

#define LEDC_LS_SIG_OUTB2_IDX			         117

#define RMT_SIG_OUTB0_IDX			         118

#define RMT_SIG_OUTB1_IDX			         119

#define RMT_SIG_OUTB2_IDX			         120

#define I2SO_DATA_OUTB_IDX			         121

#define I2SI_DATA_OUTB_IDX			         122

#define PWM_OUTB0_IDX			         123

#define PWM_OUTB1_IDX			         124

#define ATCK_IN_SEL_ADDR			GPIO_FUNC_IN_SEL25

#define ATCK_IN_SEL				GPIO_GPIO_FUNC125_IN_SEL

#define ATCK_IN_SEL_S				GPIO_GPIO_FUNC125_IN_SEL_S

#define ATCK_IN_IDX				125

#define PWM_OUTB2_IDX			         125

#define ATMS_IN_SEL_ADDR			GPIO_FUNC_IN_SEL25

#define ATMS_IN_SEL				GPIO_GPIO_FUNC126_IN_SEL

#define ATMS_IN_SEL_S				GPIO_GPIO_FUNC126_IN_SEL_S

#define ATMS_IN_IDX				126

#define PWM_OUTB3_IDX			         126

#define ATDI_IN_SEL_ADDR			GPIO_FUNC_IN_SEL25

#define ATDI_IN_SEL				GPIO_GPIO_FUNC127_IN_SEL

#define ATDI_IN_SEL_S				GPIO_GPIO_FUNC127_IN_SEL_S

#define ATDI_IN_IDX				127

#define ATDO_OUT_IDX			         127

#endif
